### ISSUE TITLE
Prototype Kodi Tease in Java

### ISSUE THREAD

**Issue by leanan-sidhelle** [leanan-sidhelle/kodi-tease#1]
# Description:
Prototype the Kodi Tease AI plugin in java to facilitate user interface development before converting to C++ and Qt/DirectX.

# Tasks
- [ ] Setup project build environment.
- [ ] Create modular application framework.
- [ ] Create default personality and media set.
- [ ] Create media database services.
- [ ] Create script running services.
- [ ] Create image display service.
- [ ] Create video display service.
- [ ] Create metronome service.
- [ ] Create text notification service.
- [ ] Create button/UI service(s).
- [ ] Create teledildonics services.
- [ ] Create estim service.
- [ ] Create text-to-speech service(s).
- [ ] Create full screen mode UI.
