### ISSUE TITLE
Setup Project Build Environment

### ISSUE THREAD

**Issue by leanan-sidhelle** [leanan-sidhelle/kodi-tease#2]
# Description
Setup a Gradle structured multi-project build environment with a SpringBoot application project.

# Tasks
- [ ] Initialize a basic java structured project (i.e. Gradle init).
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.1)
- [ ] Create a basic common-conventions from java-common-conventions (for reuse later).
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.2)
- [ ] Add versioner plugin to common-conventions.
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.3)
- [ ] Add maven-publish to common-conventions.
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.4)
- [ ] Add test, commit, revert plugin to common-conventions.
       - [ ] Test buildscripts.
       - [ ] Commit. (0.0.0.5)
- [ ] Add JaCoCo plugin to java-common-conventions.
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.6)
- [ ] Add SpotBug plugin to java-common-conventions.
     - [ ] Test buildscripts.
     - [ ] Commit. (0.0.0.7)
