### ISSUE TITLE
Create Modular Application Framework

### ISSUE THREAD

**Issue by leanan-sidhelle** [leanan-sidhelle/kodi-tease#3]
# Description
Create a SpringBoot application using the JavaFX UI system.

# Tasks
- [ ] Initialize SpringBoot project.
     - [ ] Create build.gradle, TeaseApplication, and TeaseApplicationTest using Spring Intiailizr.
     - [ ] Create a spring-application-conventions using plugins and dependencies from build.gradle.
     - [ ] Test buildscripts.
     - [ ] Commit.
- [ ] Application Classes
     - [ ] Update TeaseApplication class for use of JavaFx.
          - [ ] StageReadyEvent Class
          - [ ] StageInitializer Class
          - [ ] SpringControllerFactory Class
          - [ ] Configuration Class
          - [ ] Update TeaseApplicationTest for testing JavaFx.
          - [ ] Test build.
          - [ ] Commit.
     - [ ] Application Controller Class
          - [ ] Create TestApplicationController Class.
          - [ ] Create tease-application.fxml.
          - [ ] Update TeaseApplicationTest.
          - [ ] Test build.
          - [ ] Commit.
     - [ ] File Menu Controller Class
          - [ ] Create FileMenuController Class
          - [ ] Create file-menu.fxml and update tease-application.fxml.
          - [ ] Update TeaseApplicationTest to test file menu.
          - [ ] Test build.
          - [ ] Commit
     - [ ] Help Menu Controller Class
          - [ ] Create HelpMenuController Class
          - [ ] Create help-menu.fxml and update tease-application.fxml.
          - [ ] Update TeaseApplicationTest to test help menu.
          - [ ] Test build.
          - [ ] Commit.
     - [ ] Display Controller
          - [ ] Create TeaseDisplayController Class.
          - [ ] Create display.fxml and update tease-application.fxml.
          - [ ] Update TeaseApplicationTest to test display.
          - [ ] Test build.
          - [ ] Commit.
