### ISSUE TITLE
Create Default Personalities and Media Sets

### ISSUE THREAD

**Issue by leanan-sidhelle** [leanan-sidhelle/kodi-tease#4]
# Description
Create default personality scripts and media sets to test scripting API for Javascript and Python based scripts.  For simplicity we will use basic non-intelligent teases from Milovana.

# Tasks
- [ ] Javascript API
     - [ ] Create basic Javascript tease.
     - [ ] Create and package media set for tease.
     - [ ] Create Javascript Service.
     - [ ] TODO: add tasks for api elements
- [ ] Python API
     - [ ] Create basic Python tease.
     - [ ] Create and package media set for tease.
     - [ ] CreatePython Service.
     - [ ] TODO: add tasks for api elements
