### ISSUE TITLE
Create Media Database Services

### ISSUE THREAD

**Issue by leanan-sidhelle** [leanan-sidhelle/kodi-tease#5]
# Description
Create the APIs and initialization routines for image, video, audio, and other databases.

# Tasks
- [ ] Create Media Service
     - [ ] Create media entity.
     - [ ] Create media repository.
     - [ ] Create unit test.
     - [ ] Test build.
     - [ ] Commit.
- [ ] Create Genre Service
     - [ ] Create genre entity.
     - [ ] Create genre repository.
     - [ ] Create unit test.
     - [ ] Test build.
     - [ ] Commit.
 - [ ] Create Person Service
     - [ ] Create person entity.
     - [ ] Create person repository.
     - [ ] Create unit test.
     - [ ] Test build.
     - [ ] Commit.
- [ ] Image Database Service
     - [ ] Create image entity.
     - [ ] Create image repository.
     - [ ] Create unit test.
     - [ ] Test build.
     - [ ] Commit.
- [ ] Video Database Services
     - [ ] Create Movie Service
          - [ ] Create movie entity.
          - [ ] Create movie repository
          - [ ] Create unit test.
          - [ ] Test build.
          - [ ] Commit.
     - [ ] Create Scenes Service
          - [ ] Create scene entity.
          - [ ] Create scene repository.
          - [ ] Create unit test.
          - [ ] Test build.
          - [ ] Commit.
     - [ ] Create Shot Service
          - [ ] Create shot entity.
          - [ ] Create shot repository.
          - [ ] Create unit test.
          - [ ] Test build.
          - [ ] Commit.
- [ ] Audio Database Service
- [ ] TODO: other database services
